## Introduction to the Tensor Flow

### <b>Tensors</b>


A tensor is a generalization of vectors and matrices to potentially higher dimensions.  Internally , TensorFlow represents tensors as n-dimensional arrays of base datatypes.

It should not be surprise you that tensors are fundamental aspect of TensorFlow. They are the main objects that are passed around and manipulated throughout the program . Each tensor represents a partially defined computation that will eventually produce a value. TensorFlow programs work by building a graph of tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a datatype and a shape.

<b>Datatype Type include :</b>float32 , int32 , string and others.

<b>Shape : </b>represent the dimension of data.

#### <b>Creating Tensors</b>

Below in an exmaple of how to create some different tensors.

In [19]:
import tensorflow as tf

In [20]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(324, tf.int32)
floating = tf.Variable(3.567, tf.float64)
# All are rank 0.
string , number , floating

(<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string'>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>)

#### <b>Rank/Degree of tensors</b> 

Another word for rank is degree , these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.

Now Creating some tensors of higher degree/rank

In [21]:
# 1-D array ,rank=1
rank1_tensor = tf.Variable(["Test"] , tf.string)
# 2-D array or matrix , rank = 2 and so on......
rank2_tensor = tf.Variable([["test" , "ok"],["test" , "yes"]] , tf.string)
rank1_tensor , rank2_tensor

(<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
 array([[b'test', b'ok'],
        [b'test', b'yes']], dtype=object)>)

<b>To determine the rank of a tensor we can call the following method.</b>

In [22]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

###  Shape of tensors

Now , that we know about the rank of tensors its time to talk about the shape. The shape of a tensor is simply the amount of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

To <b>get the shape</b> of a tensor we use the shape attribute.

In [23]:
rank2_tensor.shape , rank1_tensor.shape , number.shape

(TensorShape([2, 2]), TensorShape([1]), TensorShape([]))

### Changing Shape

The number of elements of a tensor is the product of the sizes of all its shape. there are often many shapes that have the same number pf elements, making it convenient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor

In [24]:
tensor1 = tf.ones([1,2,3]) #creates a shape [1,2,3] tensor full of ones.
tensor2 = tf.reshape(tensor1 , [2,3,1]) #reshape existing data to shape [2,3,1].
tensor3 = tf.reshape(tensor2 , [3,-1]) 
# -1 tells the tensor to calculate the size of the diemension in that place
# this will reshape the tensor to  [3,2]
# the number of the element in the reshape tensor MUST match number in the original.
tensor1 , tensor2 ,tensor3

(<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
 array([[[1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

### <b>Types of tensors</b>

There are different types of tensors. the most commonly used types are :
> Variable
> Constant
> Placeholder
> SpareTensor

with the exception of variable all of these are immutable , meanning their value may not change during execution.

for now it is sufficient ot understand that we use the Variable tensor when we want to potentially change the value of our tensor.

### Evaluating Tensors

There will be some times throughtout that we need to evaluate a tensor. In other words, get its value. Since tensors represent a partially complete computation we will sometimes need to run what's called a session to evaluate the tensor.

There are many different ways to achieve this , some simpler ways are below :

In [25]:
with tf.Session() as sess : #create a session using default graph
    tensor.eval() # tensor will ofcourse be the name of tensor

AttributeError: module 'tensorflow' has no attribute 'Session'

In the code above , we evaluate the tensor variable that was stored in the default graph. The default graph holds all operations not specified to any other graph.it is possible to create our own separate graphs but for now we should stick with the default one.

Examples :

In [27]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\users\\india\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [28]:
t = tf.zeros([5,5,5,5])
t

<tf.Tensor: shape=(5, 5, 5, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

  

In [29]:
t = tf.reshape(t , [625])
t

<tf.Tensor: shape=(625,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [32]:
tf.reshape(t , [125 , -1])

<tf.Tensor: shape=(125, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0.